-- MySQL Script generated by MySQL Workbench
-- Thu Sep  1 23:45:06 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema taxi_service
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `taxi_service` ;

-- -----------------------------------------------------
-- Schema taxi_service
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `taxi_service` DEFAULT CHARACTER SET utf8 ;
USE `taxi_service` ;

-- -----------------------------------------------------
-- Table `taxi_service`.`billing`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `taxi_service`.`billing` ;

CREATE TABLE IF NOT EXISTS `taxi_service`.`billing` (
  `billing_ID` INT NOT NULL,
  `customer_ID` INT NULL,
  `location_ID` INT NULL,
  `car_ID` INT NULL,
  `total` VARCHAR(45) NULL,
  `trip_ID` INT NULL,
  PRIMARY KEY (`billing_ID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `taxi_service`.`car`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `taxi_service`.`car` ;

CREATE TABLE IF NOT EXISTS `taxi_service`.`car` (
  `car_ID` INT NOT NULL AUTO_INCREMENT,
  `car_name` VARCHAR(45) NULL,
  `car_type` VARCHAR(45) NULL,
  PRIMARY KEY (`car_ID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `taxi_service`.`chat`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `taxi_service`.`chat` ;

CREATE TABLE IF NOT EXISTS `taxi_service`.`chat` (
  `chat_ID` INT NOT NULL,
  `customer_ID` INT NULL,
  `operator_ID` INT NULL,
  PRIMARY KEY (`chat_ID`),
  CONSTRAINT `chat_ID`
    FOREIGN KEY (`chat_ID`)
    REFERENCES `taxi_service`.`customer` (`customer_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `taxi_service`.`company`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `taxi_service`.`company` ;

CREATE TABLE IF NOT EXISTS `taxi_service`.`company` (
  `company_ID` INT NOT NULL AUTO_INCREMENT,
  `company_name` VARCHAR(120) NOT NULL,
  PRIMARY KEY (`company_ID`),
  UNIQUE INDEX `taxi_company_ID_UNIQUE` (`company_ID` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `taxi_service`.`customer`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `taxi_service`.`customer` ;

CREATE TABLE IF NOT EXISTS `taxi_service`.`customer` (
  `customer_ID` INT NOT NULL,
  `trip_ID` INT NOT NULL,
  `location_ID` INT NULL,
  `shared_ID` INT NULL,
  `customer_name` VARCHAR(60) NULL,
  `customer_contact` VARCHAR(60) NULL,
  `customer_address` VARCHAR(120) NULL,
  `chat_id` INT NULL,
  `user_ID` INT NULL,
  PRIMARY KEY (`customer_ID`),
  INDEX `user_ID_idx` (`user_ID` ASC) VISIBLE,
  CONSTRAINT `user_ID`
    FOREIGN KEY (`user_ID`)
    REFERENCES `taxi_service`.`user` (`user_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `taxi_service`.`customer_location_association`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `taxi_service`.`customer_location_association` ;

CREATE TABLE IF NOT EXISTS `taxi_service`.`customer_location_association` (
  `customer_ID` INT NOT NULL,
  `location_ID` INT NOT NULL,
  PRIMARY KEY (`customer_ID`, `location_ID`),
  INDEX `location_ID_idx` (`location_ID` ASC) VISIBLE,
  CONSTRAINT `customer_ID`
    FOREIGN KEY (`customer_ID`)
    REFERENCES `taxi_service`.`customer` (`customer_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `location_ID`
    FOREIGN KEY (`location_ID`)
    REFERENCES `taxi_service`.`location` (`location_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `taxi_service`.`customer_trip_association`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `taxi_service`.`customer_trip_association` ;

CREATE TABLE IF NOT EXISTS `taxi_service`.`customer_trip_association` (
  `customer_ID` INT NOT NULL,
  `trip_ID` INT NOT NULL,
  PRIMARY KEY (`customer_ID`, `trip_ID`),
  INDEX `trip_ID_idx` (`trip_ID` ASC) VISIBLE,
  CONSTRAINT `customer_ID`
    FOREIGN KEY (`customer_ID`)
    REFERENCES `taxi_service`.`customer` (`customer_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `trip_ID`
    FOREIGN KEY (`trip_ID`)
    REFERENCES `taxi_service`.`trip` (`trip_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `taxi_service`.`driver`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `taxi_service`.`driver` ;

CREATE TABLE IF NOT EXISTS `taxi_service`.`driver` (
  `driver_ID` INT NOT NULL AUTO_INCREMENT,
  `driver_name` VARCHAR(45) NULL,
  `car_ID` INT NOT NULL,
  `user_ID` INT NULL,
  PRIMARY KEY (`driver_ID`),
  INDEX `car_ID_idx` (`car_ID` ASC) VISIBLE,
  INDEX `user_ID_idx` (`user_ID` ASC) VISIBLE,
  CONSTRAINT `car_ID`
    FOREIGN KEY (`car_ID`)
    REFERENCES `taxi_service`.`car` (`car_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `user_ID`
    FOREIGN KEY (`user_ID`)
    REFERENCES `taxi_service`.`user` (`user_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `taxi_service`.`dropoffs`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `taxi_service`.`dropoffs` ;

CREATE TABLE IF NOT EXISTS `taxi_service`.`dropoffs` (
  `dropoff_location_ID` INT NOT NULL AUTO_INCREMENT,
  `customer_ID` INT NULL,
  `driver_ID` INT NULL,
  `location_ID` INT NULL,
  PRIMARY KEY (`dropoff_location_ID`),
  INDEX `location_ID_idx` (`location_ID` ASC) VISIBLE,
  INDEX `customer_ID_idx` (`customer_ID` ASC) VISIBLE,
  CONSTRAINT `location_ID`
    FOREIGN KEY (`location_ID`)
    REFERENCES `taxi_service`.`location` (`location_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `customer_ID`
    FOREIGN KEY (`customer_ID`)
    REFERENCES `taxi_service`.`customer` (`customer_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `taxi_service`.`feedback`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `taxi_service`.`feedback` ;

CREATE TABLE IF NOT EXISTS `taxi_service`.`feedback` (
  `feedback_ID` INT NOT NULL AUTO_INCREMENT,
  `customer_ID` INT NULL,
  `driver_ID` INT NULL,
  `feedback` VARCHAR(250) NULL,
  `operator_ID` INT NULL,
  PRIMARY KEY (`feedback_ID`),
  INDEX `customer_ID_idx` (`customer_ID` ASC) VISIBLE,
  INDEX `driver_ID_idx` (`driver_ID` ASC) VISIBLE,
  INDEX `operator_ID_idx` (`operator_ID` ASC) VISIBLE,
  CONSTRAINT `customer_ID`
    FOREIGN KEY (`customer_ID`)
    REFERENCES `taxi_service`.`customer` (`customer_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `driver_ID`
    FOREIGN KEY (`driver_ID`)
    REFERENCES `taxi_service`.`driver` (`driver_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `operator_ID`
    FOREIGN KEY (`operator_ID`)
    REFERENCES `taxi_service`.`operator` (`operator_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `taxi_service`.`location`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `taxi_service`.`location` ;

CREATE TABLE IF NOT EXISTS `taxi_service`.`location` (
  `location_ID` INT NOT NULL,
  `location_address` VARCHAR(120) NULL,
  PRIMARY KEY (`location_ID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `taxi_service`.`operator`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `taxi_service`.`operator` ;

CREATE TABLE IF NOT EXISTS `taxi_service`.`operator` (
  `operator_ID` INT NOT NULL,
  `operator_name` VARCHAR(120) NULL,
  `customer_ID` INT NULL,
  `billing_ID` INT NULL,
  `car_ID` INT NULL,
  `location_ID` INT NULL,
  `chat_ID` INT NULL,
  `user_ID` INT NULL,
  PRIMARY KEY (`operator_ID`),
  INDEX `billing_ID_idx` (`billing_ID` ASC) VISIBLE,
  INDEX `chat_ID_idx` (`chat_ID` ASC) VISIBLE,
  INDEX `user_ID_idx` (`user_ID` ASC) VISIBLE,
  CONSTRAINT `billing_ID`
    FOREIGN KEY (`billing_ID`)
    REFERENCES `taxi_service`.`billing` (`billing_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `chat_ID`
    FOREIGN KEY (`chat_ID`)
    REFERENCES `taxi_service`.`chat` (`chat_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `user_ID`
    FOREIGN KEY (`user_ID`)
    REFERENCES `taxi_service`.`user` (`user_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `taxi_service`.`pickups`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `taxi_service`.`pickups` ;

CREATE TABLE IF NOT EXISTS `taxi_service`.`pickups` (
  `pickup_location_ID` INT NOT NULL AUTO_INCREMENT,
  `customer_ID` INT NULL,
  `driver_ID` INT NULL,
  `location_ID` INT NULL,
  PRIMARY KEY (`pickup_location_ID`),
  INDEX `location_ID_idx` (`location_ID` ASC) VISIBLE,
  INDEX `customer_ID_idx` (`customer_ID` ASC) VISIBLE,
  CONSTRAINT `location_ID`
    FOREIGN KEY (`location_ID`)
    REFERENCES `taxi_service`.`location` (`location_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `customer_ID`
    FOREIGN KEY (`customer_ID`)
    REFERENCES `taxi_service`.`customer` (`customer_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `taxi_service`.`trip`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `taxi_service`.`trip` ;

CREATE TABLE IF NOT EXISTS `taxi_service`.`trip` (
  `trip_ID` INT NOT NULL,
  `pickup_locatiion_ID` INT NULL,
  `dropoff_location_ID` INT NULL,
  `billing_ID` INT NULL,
  `customer_ID` INT NULL,
  PRIMARY KEY (`trip_ID`),
  INDEX `billing_ID_idx` (`billing_ID` ASC) VISIBLE,
  CONSTRAINT `billing_ID`
    FOREIGN KEY (`billing_ID`)
    REFERENCES `taxi_service`.`billing` (`billing_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `taxi_service`.`user`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `taxi_service`.`user` ;

CREATE TABLE IF NOT EXISTS `taxi_service`.`user` (
  `user_ID` INT NOT NULL,
  `company_ID` INT NULL,
  PRIMARY KEY (`user_ID`),
  INDEX `company_ID_idx` (`company_ID` ASC) VISIBLE,
  CONSTRAINT `company_ID`
    FOREIGN KEY (`company_ID`)
    REFERENCES `taxi_service`.`company` (`company_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
